export const HAS_ERRORED = 'HAS_ERRORED';
export const IS_LOADING = 'IS_LOADING';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const POST_RATING_SUCCESS = 'POST_RATING_SUCCESS';
export const DELETE_RATING_SUCCESS = 'DELETE_RATING_SUCCESS';
